language: c++

os:
  - linux
  - osx

env:
  matrix:
      - BUILD_TYPE=Debug
      - BUILD_TYPE=Release

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5
      - clang-3.8
      - cmake
      - cmake-data
      - libeigen3-dev

install:
  - if [ "$CXX" == "g++" ];     then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update                ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install llvm@3.8 gcc@5 eigen; fi

script:
  - mkdir build ; cd build
  - cmake -DCMAKE_INSTALL_PREFIX=../install ..
  - cmake --build . --config $BUILD_TYPE
  - cmake --build . --target install
